services:
  db:
    image: postgres
    container_name: postgres_container
    hostname: postgres
    environment:
      POSTGRES_USER: alysson
      POSTGRES_PASSWORD: senhabanco
      POSTGRES_DB: item_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    runtime: nvidia
    restart: unless-stopped

volumes:
  postgres-data: